### ISSUE TITLE
Error on https://huggingface.co/spaces/nllg/DeTikZify

### ISSUE THREAD

**Issue by quark67** [potamides/DeTikZify#9]
All I see is:

Runtime error
Scheduling failure: unable to schedule
Container logs:

===== Application Startup =====

<img width="724" alt="Image" src="https://github.com/user-attachments/assets/9b26bbba-040c-4347-b764-d9ffb570e34c" />

Is there a way to use this?

**Comment by potamides** [comment]
Thanks for reporting! Seems like a [general issue](https://discuss.huggingface.co/t/scheduling-failure-error-in-hf/139173/5) with HuggingFace right now. Our space seems to be working again now, so hoping that the problem has been fixed on their end.

**Comment by quark67** [comment]
Yes, it works now. Perhaps can you add a tip about this issue: what to do when there is a similar issue. I was aware about the DeTikZify tool when this publication has write about it: https://publications.gutenberg-asso.fr/lettre/issue/view/lettre53-2024 (bottom of page 66), but when I tried (at october-november 2024) I had the same issue.

**Comment by svozil** [comment]
I experience similar problems as [quark67](https://github.com/quark67)
opened [on Feb 7](https://github.com/potamides/DeTikZify/issues/9#issue-2839000933)

**Comment by XDzzzzzZyq** [comment]
Still not working.... I got the same error:

runtime error
Scheduling failure: unable to schedule
Container logs:

Failed to retrieve error logs: SSE is not enabled

**Comment by potamides** [comment]
It is running again. `Scheduling failure: unable to schedule` indicates a problem with the HuggingFace servers and can usually be fixed with a simple restart of the space. I am not aware of a simple way to do this automatically so I have pinned this issue for now, so that users can ping me more easily and I can restart it manually.

**Comment by MadanPrj** [comment]
Hugging Face Silence Remover from Audio is not Working it is showing run time error. How to solve it ?
